version: '3.8'

services:
  app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    container_name: infnet-guia-website
    stdin_open: true
    ports:
      - 3000:3000

  database:
    extends:
      file: docker-compose.database.yaml
      service: database

  # prometheus:
  #   image: prom/prometheus
  #   container_name: prometheus
  #   ports:
  #     - "9090:9090"
  #   volumes:
  #     - ./monitor/prometheus.yml:/etc/prometheus/prometheus.yml

  # grafana:
  #   image: grafana/grafana
  #   container_name: grafana
  #   ports:
  #     - "3001:3000"
  #   environment:
  #     - GF_SECURITY_ADMIN_PASSWORD=admin
  #   volumes:
  #     - grafana_data:/var/lib/grafana

  # k6:
  #   image: grafana/k6
  #   container_name: k6
  #   volumes:
  #     - ./monitor/scripts:/scripts
  #   command: run /scripts/teste.js

volumes:
  mysql_data:
  #grafana_data:
