apiVersion: apps/v1
kind: Deployment
metadata:
  name: guia-infnet
spec:
  replicas: 4
  selector:
    matchLabels:
      app: guia-infnet
  template:
    metadata:
      labels:
        app: guia-infnet
    spec:
      containers:
        - name: guia-infnet
          image: rafaelleite7/guia-infnet
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
