apiVersion: batch/v1
kind: Job
metadata:
  name: k6-load-test
spec:
  template:
    spec:
      containers:
        - name: k6
          image: grafana/k6
          command: ["k6", "run", "-"]
          stdin: true
          tty: true
          args:
            - |
              import http from 'k6/http';
              import { sleep, check } from 'k6';

              export let options = {
                vus: 10,
                duration: '30s',
              };

              export default function () {
                let res = http.get('http://guia-infnet:3000');
                check(res, { 'status was 200': (r) => r.status === 200 });
                sleep(1);
              }
      restartPolicy: Never
  backoffLimit: 0
