apiVersion: v1
kind: Service
metadata:
  name: guia-infnet
spec:
  type: NodePort
  selector:
    app: guia-infnet
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30080
      