name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar pnpm com Corepack
        run: |
          corepack enable
          corepack prepare pnpm@10.5.2 --activate
          pnpm --version

      - name: Instalar dependências
        run: pnpm install

      - name: Build do projeto
        run: pnpm build

      - name: Login no Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build da imagem Docker
        run: docker build -t ${{ secrets.REGISTRY }}/${{ secrets.IMAGE_NAME }}:latest .

      - name: Push da imagem pro Docker Hub
        run: docker push ${{ secrets.REGISTRY }}/${{ secrets.IMAGE_NAME }}:latest

#      - name: Deploy para Kubernetes
#        uses: azure/k8s-deploy@v1
#        with:
#          manifests: |
#            ./k8s/deployment.yaml
#            ./k8s/service.yaml
#          images: |
#           ${{ secrets.REGISTRY }}/${{ secrets.IMAGE_NAME }}:latest
#          namespace: default

          
